version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: flyn_db
    environment:
      POSTGRES_USER: flyn_user
      POSTGRES_PASSWORD: flyn_password
      POSTGRES_DB: flyn_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
