apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lynq-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - api.lynq.finance
    - app.lynq.finance
    secretName: lynq-tls
  rules:
  - host: api.lynq.finance
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lynq-backend-service
            port:
              number: 80
  - host: app.lynq.finance
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lynq-frontend-service
            port:
              number: 80
